### PR TITLE
Update pubspec.yaml

### PR DESCRIPTION
**Pull request by gonojuarez**
The last version of Flutter Web is 1.0.0,
I propose this change to get security with the latest version of flutter

### CODE REVIEW

**Comment by bschmalb** [comment]
Let's merge this please

**Comment by omar-hanafy** [comment]
lots of dependencies are depending on Web 1.0.0 now, lets please get this merged!

**Comment by aelahmar** [comment]
@Lyokone  @gonojuarez 
When this PR will be Merged [PLEASE]?

**Comment by bartekpacia** [comment]
Superseded by #1002 and #1003.

**Pull request closed without merging**
