### PR TITLE
Make LocationData latitude/longitude not null

### PR DESCRIPTION
**Pull request by danielgomezrico**
The current declaration of attributes on `LocationData` class does not make sense to me because all the attributes are nullable, why do you want to have a `LocationData` without location values?

Fix: https://github.com/Lyokone/flutterlocation/issues/675

### CODE REVIEW

**Comment by danielgomezrico** [comment]
@Lyokone any chance to take a look at this?

**Comment by bartekpacia** [comment]
This sounds like a valid change.

When I release changes from #847 I'll take a look at this.

**Comment by bartekpacia** [comment]
Hi @danielgomezrico, could you rebase with latest `master`?

**Comment by danielgomezrico** [comment]
@bartekpacia done :)

**Comment by bartekpacia** [comment]
Nice! TBH I wasn't expecting you to respond after 2 years :) Thank you.

Could you also resolve CI failures? That should be enough to get this merged.

**Comment by bartekpacia** [comment]
no response

**Pull request closed without merging**
