### PR TITLE
iOS LocationPlugin rewritten in Objective-C instead of Swift

### PR DESCRIPTION
**Pull request by fluff**
Hi there, I've rewritten the iOS native LocationPlugin code from Swift to Objective-C, in order to resolve the various dependency issues mentioned in https://github.com/Lyokone/flutterlocation/issues/4

Does this look alright?

### CODE REVIEW

**Comment by Lyokone** [comment]
Thanks a lot for this commit !

**Comment by fluff** [comment]
My pleasure :)

**Comment by BenSower** [comment]
image

**Comment by BenSower** [comment]
Me and the rest of our app-devs right now
Me and the rest of our app-devs right now

**Pull request merged**
