### PR TITLE
fix #784: NullPointerException when building location data

### LINKED ISSUE #784: fix: version 5.0.0-dev.8 getLocation() causes fatal error on android device
**Description**
Running getLocation using version 5.0.0-dev.8 causes fatal error on Pixel 4 running API 30 android 11

Location permissions: Always

With the error: 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference

Error comes from LocationPlugin.kt line 153:
.setSatellites(location.extras.getInt("satellites").toLong())

Seems to be working if line is commented, however I have not read through the code enough to understand the implications of removing this line.

**Expected behavior**
Expected to recieve the position of the device

**Steps To Reproduce**

Run getLocation() on Android device (API 30 android 11) at any point, with location permission Always granted

**Tested on:**

- Android, API Level 30, simulator

**Additional logs**

D/Location(10166): onPermissionGranted
D/LOCATION(10166): 55.7093464 13.200616
D/AndroidRuntime(10166): Shutting down VM
E/AndroidRuntime(10166): FATAL EXCEPTION: main
E/AndroidRuntime(10166): Process: com.rootpi.time_tracker, PID: 10166
E/AndroidRuntime(10166): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
E/AndroidRuntime(10166): 	at com.lyokone.location.LocationPlugin.onLocationChanged(LocationPlugin.kt:153)
E/AndroidRuntime(10166): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationChanged(GooglePlayServicesLocationProvider.java:119)
E/AndroidRuntime(10166): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLastKnowLocationTaskReceived(GooglePlayServicesLocationProvider.java:211)
E/AndroidRuntime(10166): 	at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource$3.onComplete(GooglePlayServicesLocationSource.java:92)
E/AndroidRuntime(10166): 	at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.1:1)
E/AndroidRuntime(10166): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(10166): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10166): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(10166): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(10166): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10166): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(10166): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (10166): Sending signal. PID: 10166 SIG: 9
Lost connection to device.

### PR DESCRIPTION
**Pull request by speshiou**
## Description
Android app will crash when getting current location, many users encounter the same issue (#784).

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
        at com.lyokone.location.LocationPlugin.onLocationChanged(LocationPlugin.kt:153)
        at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLocationChanged(GooglePlayServicesLocationProvider.java:119)
        at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationProvider.onLastKnowLocationTaskReceived(GooglePlayServicesLocationProvider.java:211)
        at com.lyokone.location.location.providers.locationprovider.GooglePlayServicesLocationSource$3.onComplete(GooglePlayServicesLocationSource.java:92)
        at com.google.android.gms.tasks.zzi.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7872)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
Based on [official docs](https://developer.android.com/reference/android/location/Location#getExtras()), the extras property of `Location` may be null, so do null-safety call when building location data.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by dohji** [comment]
Please has this been merged. I'm having this issue and I'll be glad if it can be fixed as soon as possible

**Comment by fairuzmn** [comment]
@speshiou great patch!

**Comment by ThickLine** [comment]
@Lyokone It's so hard to merge it? If you cannot maintain a package that you clearly can't hand over to someone that is willing to do so.

**Comment by bartekpacia** [comment]
> It's so hard to merge it? If you cannot maintain a package that you clearly can't hand over to someone that is willing to do so.

Wow, that great guy created a package **in his free time** for you to use it **for free**, and you have the audacity to demand more from him?

**Comment by bartekpacia** [comment]
I'm going to close this PR since it targets the old `v5.0.0-dev.8` branch, which is discontinued. See #870 and #846 to learn more about this.

**Pull request closed without merging**
