### PR TITLE
Migration to AndroidX

### LINKED ISSUE #107: AndroidX Support
## AndroidX Support

Google has updates all their flutter dependencies, what causes to migrate to AndroidX libs.
Unfortunately this plugin crashes after migration. 

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

UPDATE:
just wanted to add the error message from console:

```
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:10: error: package android.support.annotation does not exist
import android.support.annotation.MainThread;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:11: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:12: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
C:\flutter\.pub-cache\hosted\pub.dartlang.org\location-1.4.1\android\src\main\java\com\lyokone\location\LocationPlugin.java:289: error: cannot find symbol
            public void onFailure(@NonNull Exception e) {
                                   ^
  symbol: class NonNull
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

### PR DESCRIPTION
**Pull request by vladaman**
Migration to AndroidX to support newer Flutter. Fixes #107

### CODE REVIEW

**Comment by dimmetrius** [comment]
👍

**Comment by Lyokone** [comment]
Thanks for your contribution ! :)

**Comment by kevinkicho** [comment]
Hi, guys~ When will the new version released on flutter package?  Thanks for your attention on this...
https://pub.dartlang.org/packages/location

**Comment by Lyokone** [comment]
Hey ! I'll do it tonight ! :)

**Comment by tolotrasamuel** [comment]
Hello! Is the new version released on flutter package? I couldn't compile the https://pub.dartlang.org/packages/location today with AndroidX

**Pull request merged**
