### PR TITLE
Fix, cleaner code

### LINKED ISSUE #6: Get oneshot updated location :)
Can you implement a way to get oneshot updated location, currently getLocation retrieves the last known location not an updated :/ and i don't want to use a listener.
thx :)

### PR DESCRIPTION
**Pull request by Alexays**
Ok so in this PR what i have done : 
 - close #6 
 - Cleaner android code
 - Better Android permission support
ex: Opens settings to enable location
 - Fix: stream will not close

Open to review :)

### CODE REVIEW

**Comment by Lyokone** [comment]
Hi I cannot find the `firstWhere` function in your code, is it implemented ? :)

**Comment by Alexays** [comment]
@Lyokone firstWhere is a dart function ;)

**Comment by Lyokone** [comment]
Oh okay didn't knew that ! Thanks !

**Comment by Lyokone** [comment]
Thanks a lot !! :)

**Pull request merged**
