### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by linhnguyen-gt**
fix compile error, 502 bad gateway
upgrade version 'com.google.android.gms:play-services-location:16.+'  -> 'com.google.android.gms:play-services-location:17.0.0'

### CODE REVIEW

**Comment by felix-ht** [comment]
This is causing a ton of issues as 16.+ cannot be resolved properly anymore.
e.g.: https://github.com/flutter-mapbox-gl/maps/runs/4843224040?check_suite_focus=true

Would be great if this could be merged an released.

@Lyokone

**Comment by tattivitorino** [comment]
please merge this fix... i've seen so many people having this problem including me

**Comment by felix-ht** [comment]
not stale!

**Comment by bartekpacia** [comment]
Will be fixed by #847.

**Pull request closed without merging**
