### PR TITLE
allow for Android notification customization

### PR DESCRIPTION
**Pull request by kevlatus**
This PR adds a new method to the `LocationPlatform` interface, as discussed in #483 
```dart
Future<bool> changeNotificationOptions({
  String channelName,
  String title,
  String iconName,
  String subtitle,
  String description,
  Color color,
  bool onTapBringToFront,
});
```

It allows for changing the sticky notification on Android before, during and after `enableBackgroundMode` is called. The current default behavior does not change.

Merging and publishing this PR is highly appreciated, as well as any feedback on the implementation.

Best
Kevin

### CODE REVIEW

**Comment by Lyokone** [comment]
Hi ! Thanks a lot for this PR, I'll try to look into it really soon !

**Comment by Lyokone** [comment]
Looks really good to me, I would like to have the null safety merged into master first, then I'll be able to rebase your PR if you don't have the time to do it :)

**Comment by kevlatus** [comment]
Great! Is there any help required for null safety? I could help out, if necessary!

Otherwise just give me a heads up once master is ready for this PR 👍

**Comment by Lyokone** [comment]
Thanks for your help, but it was not that hard, I also went with Melos to make package release easier, null safety is on master :)

**Comment by kevlatus** [comment]
I just realized that rebase doesn't really work since the packages have moved to the "packages" subfolder on master.
Either you know handy trick to rebase nevertheless or I will take some time this week to create a new PR forked from the current master.

**Pull request closed without merging**
