### PR TITLE
* fix #620 bug and #864 bug

### LINKED ISSUE #620: Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.lyokone.location.FlutterLocationService$a
Have seen this error twice on our production app.

Galaxy Z Fold2 5G
Android Version: 11

```
Fatal Exception: java.lang.ClassCastException: android.os.BinderProxy cannot be cast to com.lyokone.location.FlutterLocationService$a
       at com.lyokone.location.LocationPlugin$1.onServiceConnected(LocationPlugin.java:24)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:2084)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2116)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### LINKED ISSUE #864: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
**Describe the bug**
App crashing on very first app open

**Tested on:**
 - Android OS 13, Samsung Galaxy M13

**Other plugins:**
 - List of others Flutter plugins that could interfere

**Additional logs**
D/FlutterGeolocator(20666): Attaching Geolocator to activity
D/FlutterGeolocator(20666): Detaching Geolocator from activity
E/AndroidRuntime(20666): FATAL EXCEPTION: main
E/AndroidRuntime(20666): Process: com.skieats.owner, PID: 20666
E/AndroidRuntime(20666): java.lang.RuntimeException: Unable to destroy activity {com.skieats.owner/com.skieats.owner.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(20666): 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:6080)
E/AndroidRuntime(20666): 	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6113)
E/AndroidRuntime(20666): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6460)
E/AndroidRuntime(20666): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6341)
E/AndroidRuntime(20666): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
E/AndroidRuntime(20666): 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
E/AndroidRuntime(20666): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(20666): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(20666): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
E/AndroidRuntime(20666): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(20666): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(20666): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(20666): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(20666): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20666): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(20666): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(20666): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.plugin.common.PluginRegistry$RequestPermissionsResultListener com.lyokone.location.FlutterLocationService.getServiceRequestPermissionsResultListener()' on a null object reference
E/AndroidRuntime(20666): 	at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:117)
E/AndroidRuntime(20666): 	at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java:56)

### PR DESCRIPTION
**Pull request by wtwsky**
fix #620 bug and fix #864 bug

### CODE REVIEW

**Comment by bartekpacia** [comment]
Did anyone test this and can confirm it indeed works?

**Comment by alaincruz06** [comment]
Any follow-up on this?

**Comment by bartekpacia** [comment]
I can merge this but I haven't tested this change myself. Did you check it?

**Comment by alaincruz06** [comment]
Was going to using the PR-ed branch from @wtwsky but it's "31 commits behind", think it'll be safer to fork it myself and copy the changes. In the meantime @wtwsky can you update your forked repo and try?

**Comment by ardeshir-33033** [comment]
@alaincruz06 
Please don't forget to update us on this matter.
I cannot use this fork it has errors on pub get

**Comment by alaincruz06** [comment]
@ardeshir-33033 @bartekpacia I have good news, I can confirm (after forking the library-from master branch-, running the changes on this PR in [LocationPlugin.java](https://github.com/Lyokone/flutterlocation/pull/889/files#diff-7405aad6d6cb6e557f64b9a5722697079be56c2831252743b95a5432312c3725), and testing the library) ,it works!!

I personally can't share my forked version of the repo because it is in a private repo, but it's easy to replicate, just:
1. Fork master branch
2. Execute the changes from this PR
3. Then make a PR or merge.

**Comment by bartekpacia** [comment]
Thanks, I'm merging this and releasing.

**Pull request merged**
