### PR TITLE
bugFix serviceEnabled() always gives TRUE results

### PR DESCRIPTION
**Pull request by mustofin**

### CODE REVIEW

**Comment by tohami** [comment]
why this bull request not merged?

**Comment by Lyokone** [comment]
Hey, I was away from my computer for a long time so it got staled, I will unstack the staled PRs to see If I haven't missed anything..

**Comment by Lyokone** [comment]
According to my latest tests, the serviceEnabled() function is working properly. Do you have some devices on which it doesn't works ?

**Comment by YahiaRagae** [comment]
Yes, I'm using v3.0.2 on Xiaomi Redmi 4A and the issue is still happening `serviceEnabled()` is always returning true even when the location service is disabled

**Pull request closed without merging**
