### PR TITLE
Build on and support Android 12 (SDK 31).

### LINKED ISSUE #639: Build on and support Android 12 (SDK 31), i.e. use FLAG_IMMUTABLE for PendingIntent
**Describe the bug**
When building an app using `location`on Android 12 (SDK 31) there's a runtime crash because the `PendingIntent` needs to have a flag for its (im)mutability.

**Expected behavior**
Plugin to not break an app when building on Android 12.

**Tested on:**
 - Android, API Level 31, Google Pixel 3a
 - Android, API Level 31, Google Pixel 5

**Additional logs**
``` shell
2021-09-28 13:51:59.445 26410-26505/com.philips.lighting.hue2.daily E/AndroidRuntime: FATAL EXCEPTION: pool-19-thread-1
    Process: [redacted_applicaton_id], PID: 26410
    java.lang.IllegalArgumentException: [redacted_applicaton_id]: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:273)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:151)
        at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:171)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:102)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

### LINKED ISSUE #702: Android 12 issue changeNotificationOptions parameter onTapBringToFront
Just On Android 12 when I call **location.changeNotificationOptions** with the parameter **onTapBringToFront = true** flutter generates the error below 

```
E/flutter ( 6703): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(CHANGE_NOTIFICATION_OPTIONS_ERROR, An unexpected error happened during notification options change:com.smartinteragerisk: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/flutter ( 6703): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles., null, null)

```

I tested in   Android, API 31  simulator and  real device

Someone can help me?

### PR DESCRIPTION
**Pull request by PieterAelse**
Fixes #639 
Fixes #702

### CODE REVIEW

**Comment by chedwin41** [comment]
Hi @Lyokone, could you have a quick look to this PR ? This is the only package left so I can migrate my app to Android 12.
Thanks a lot !

**Comment by PieterAelse** [comment]
@Lyokone any updates on merging this PR to unblock everybody from building on Android 12?

**Comment by magnuswikhog** [comment]
@Lyokone Any plans to merge this pull request in the near future? This issue is really blocking a lot of app releases.

**Comment by rubenaster** [comment]
@Lyokone any updates on that current topic? Can we help? Unfortunately this prevents Android 12 devices from running the application.

**Comment by note11g** [comment]
@Lyokone Please merge this PR....

**Comment by PieterAelse** [comment]
Did not try it myself, but in the mean-time maybe everybody who is blocked can use the following:

```xml
dependencies:
  kittens:
    git:
      url: git@github.com:pieteraelse/flutterlocation.git
      ref: build_on_and_support_android_12_sdk_31
```

**Comment by carloserazo47** [comment]
> Did not try it myself, but in the mean-time maybe everybody who is blocked can use the following:
> 
> ```
> dependencies:
>   flutterlocation:
>     git:
>       url: git@github.com:pieteraelse/flutterlocation.git
>       ref: build_on_and_support_android_12_sdk_31
> ```
> 
> Source: https://dart.dev/tools/pub/dependencies#git-packages

Thanks @PieterAelse, you have to set the path as well:

```
dependencies:
  location:
      git:
        url: https://github.com/PieterAelse/flutterlocation.git
        path: packages/location
        ref: issue_639/build_on_and_support_android_12_sdk_31
```

**Comment by PieterAelse** [comment]
@Lyokone trying to unflag as it's not stale

**Comment by akhatriST** [comment]
@Lyokone Any chance of the PR getting merged of the fix? 

btw How is everyone tackling this issue?

**Comment by lukaskurz** [comment]
@akhatriST I just forked the repo, merged the contents of all the PRs which were needed and use that repo for now.

**Comment by xunreal75** [comment]
Can you try to contribute your fork.
The package has no changes since 3 months.

Doesn’t know whether package is orbaned orphaned/abandoned 

Thanks

**Comment by Cotspheer** [comment]
@Lyokone any chance to get this merged?

**Comment by PieterAelse** [comment]
@bartekpacia Since you closed #639 in favor of #702  (a newer issue? but okay..), could you review this PR to get it merged?

**Comment by bartekpacia** [comment]
Will take a look at it soon and hopefully merge

> a newer issue? but okay..

I was just trying to clean up the repo, many issues had often ~5 duplicates, so I wasn't really looking which one was newer

**Comment by bartekpacia** [comment]
The build is failing.

**Comment by PieterAelse** [comment]
@bartekpacia Looks like the main change of my PR is already done on master now: https://github.com/Lyokone/flutterlocation/commit/187734cc24a3495f6d90296bc3ce24ce4fc8242d 

Maybe this PR can be closed, if you agree.

**Comment by bartekpacia** [comment]
Yeah, looks like it. Sorry for that coincidence, I just wanted to release the fix asap. Thank you for the contribution nevertheless!

**Pull request closed without merging**
