### PR TITLE
Fix testing doc

### PR DESCRIPTION
**Pull request by Leffe108**
## Description

Resolves https://github.com/Lyokone/flutterlocation/issues/790 by updating the testing docs to a solution that works. (if you import the required packages)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by guyluz11** [comment]
Do you know if this solves tests for current pr not passing?

**Comment by Leffe108** [comment]
> Do you know if this solves tests for current pr not passing?

I am not quite sure I understand your question.

This PR fixes/improves the documentation of flutter_location. The issue https://github.com/Lyokone/flutterlocation/issues/790 contains information that if you follow the current docs it suggests using `setLocationInstance()` method in the library, but there is no such method in current stable. So you cannot mock the location class in your tests.

Here is an example test where I use the solution in this PR to write a test for an app that uses this package:
https://github.com/Leffe108/shapes-outdoor2/blob/198093ed4c76d7fed81b1c4d73b412336afd62d1/test/screen_nav_test.dart#L44

**Comment by guyluz11** [comment]
Ho ok, 

I was talking about the git-actions not passing for pr's 

image


But now I understand that this pr is not for that, thanks.

**Comment by Leffe108** [comment]
I dived a bit further. It seems that `setLocationInstance` is added by 619e8c53a51feaf598fd5fb467a4c4c2ddc82d23 and is part of upcomming 5.0 release. But is already shown as a solution on the docs website: https://docs.page/Lyokone/flutterlocation/testing . To be fair though this docs website is not linked to directly on pub.dev, but from the github README.md of master channel.

So.. perhaps just close this PR and the issue which will help any user of < 5.0 to write tests and this will resolve once 5.0 is ready for stable.

**Pull request closed without merging**
